/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_LoaiPhong;
import BLL.BLL_Phong;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author LGNV
 */
public class dialogFormLoaiPhong extends javax.swing.JDialog {

    /**
     * Creates new form FormPhong
     */
    public dialogFormLoaiPhong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        css();

    }

    public void css() {
        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));

    }

    String ID = "";
    boolean checkNew = true;

    public void checkNew(boolean check) {
        checkNew = check;
        if (checkNew) {
            btnDelete.setVisible(false);
            btnThem.setText("Thêm");
        } else {
            ID = BLL_LoaiPhong.getIDTable();
            btnDelete.setVisible(true);
            btnThem.setText("Cập Nhật");
            BLL_LoaiPhong.setDataToForm(ID);
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lgnvPanel1 = new LIBRARY.lgnvPanel();
        txtTenLoaiPhong = new LIBRARY.lgnvTextField();
        lblErrorTenPhong = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGiaPhong = new LIBRARY.lgnvTextField();
        lblErrorGiaPhong = new javax.swing.JLabel();
        btnThem = new LIBRARY.lgnvButton();
        btnClose = new LIBRARY.lgnvButton();
        btnDelete = new LIBRARY.lgnvButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMoTa = new LIBRARY.lgnvTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        lgnvPanel1.setBackground(new java.awt.Color(255, 255, 255));
        lgnvPanel1.setLGNV_ShaDownAllow(true);
        lgnvPanel1.setLGNV_ShadownColor(100);
        lgnvPanel1.setLGNV_ShadownPixel(40);
        lgnvPanel1.setLGNV_lineAllow(false);
        lgnvPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTenLoaiPhong.setLGNV_placeholderText("Nhập Tên Phòng");
        lgnvPanel1.add(txtTenLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 138, 285, 41));

        lblErrorTenPhong.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorTenPhong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblErrorTenPhong.setText("Không được để trống tên phòng");
        lgnvPanel1.add(lblErrorTenPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 185, 285, -1));

        jLabel4.setText("Giá Phòng");
        lgnvPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 211, -1));

        txtGiaPhong.setLGNV_placeholderText("Nhập Tên Phòng");
        lgnvPanel1.add(txtGiaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 285, 41));

        lblErrorGiaPhong.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorGiaPhong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblErrorGiaPhong.setText("  ");
        lgnvPanel1.add(lblErrorGiaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 285, -1));

        btnThem.setBackground(new java.awt.Color(100, 89, 242));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setLGNV_ShadowAllow(true);
        btnThem.setLGNV_borderRadius(60);
        btnThem.setLGNV_lineAllow(false);
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        lgnvPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 194, 79));

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_close_window_25px_1.png"))); // NOI18N
        btnClose.setLGNV_backgroundAllow(false);
        btnClose.setLGNV_hoverAllow(false);
        btnClose.setLGNV_lineAllow(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        lgnvPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 26, 38, 32));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_remove_25px.png"))); // NOI18N
        btnDelete.setLGNV_backgroundAllow(false);
        btnDelete.setLGNV_hoverAllow(false);
        btnDelete.setLGNV_lineAllow(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        lgnvPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 38, 32));

        jLabel6.setText("Tên Loại Phòng");
        lgnvPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 211, -1));

        jLabel1.setBackground(new java.awt.Color(100, 89, 242));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 89, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Loại Phòng");
        lgnvPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 390, 50));

        jLabel5.setText("Mô Tả");
        lgnvPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 211, -1));

        txtMoTa.setLGNV_placeholderText("Nhập Tên Phòng");
        lgnvPanel1.add(txtMoTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 285, 41));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lgnvPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (BLL_LoaiPhong.checkValidate()) {
            if (checkNew) {
                BLL_LoaiPhong.insert(BLL_LoaiPhong.getDataForm());

            } else {
                BLL_LoaiPhong.update(BLL_LoaiPhong.getDataForm());
            }
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnThemActionPerformed


    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        BLL_LoaiPhong.deleteByID(ID);
        this.setVisible(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogFormLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogFormLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogFormLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogFormLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogFormLoaiPhong dialog = new dialogFormLoaiPhong(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIBRARY.lgnvButton btnClose;
    private LIBRARY.lgnvButton btnDelete;
    private LIBRARY.lgnvButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel lblErrorGiaPhong;
    public javax.swing.JLabel lblErrorTenPhong;
    private LIBRARY.lgnvPanel lgnvPanel1;
    public LIBRARY.lgnvTextField txtGiaPhong;
    public LIBRARY.lgnvTextField txtMoTa;
    public LIBRARY.lgnvTextField txtTenLoaiPhong;
    // End of variables declaration//GEN-END:variables
}
