/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author LGNV
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBG = new LIBRARY.lgnvPanel();
        lblBG = new LIBRARY.lgnvPanel();
        lblLogin = new javax.swing.JLabel();
        txtUser = new LIBRARY.lgnvTextField();
        txtPass = new LIBRARY.lgnvTextField();
        btnLogin = new LIBRARY.lgnvButton();
        pnlBG3 = new LIBRARY.lgnvPanel();
        lgnvButton1 = new LIBRARY.lgnvButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlBG.setBackground(new java.awt.Color(255, 255, 255));
        pnlBG.setLGNV_lineAllow(false);
        pnlBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBG.setBackground(new java.awt.Color(255, 255, 255));
        lblBG.setLGNV_ShaDownAllow(true);
        lblBG.setLGNV_ShadownOpactity(50);
        lblBG.setLGNV_ShadownPixel(20);
        lblBG.setLGNV_lineAllow(false);

        lblLogin.setBackground(new java.awt.Color(100, 89, 242));
        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(100, 89, 242));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Đăng Nhập");

        txtUser.setLGNV_iconLeft(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_user_male_25px.png"))); // NOI18N
        txtUser.setLGNV_iconLeftPadding(20);
        txtUser.setLGNV_placeholderText("Tên Đăng Nhập");
        txtUser.setLGNV_radius(50);

        txtPass.setLGNV_iconLeft(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_user_male_25px.png"))); // NOI18N
        txtPass.setLGNV_iconLeftPadding(20);
        txtPass.setLGNV_placeholderText("Mật Khẩu");
        txtPass.setLGNV_radius(50);

        btnLogin.setBackground(new java.awt.Color(100, 89, 242));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Đăng Nhập");
        btnLogin.setLGNV_borderRadius(60);
        btnLogin.setLGNV_lineAllow(false);
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblBGLayout = new javax.swing.GroupLayout(lblBG);
        lblBG.setLayout(lblBGLayout);
        lblBGLayout.setHorizontalGroup(
            lblBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBGLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBGLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(lblBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBGLayout.createSequentialGroup()
                        .addGroup(lblBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBGLayout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );
        lblBGLayout.setVerticalGroup(
            lblBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBGLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pnlBG.add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 310, 410));

        pnlBG3.setBackground(new java.awt.Color(100, 89, 242));
        pnlBG3.setLGNV_lineAllow(false);

        lgnvButton1.setBackground(new java.awt.Color(255, 255, 255));
        lgnvButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_close_window_25px.png"))); // NOI18N
        lgnvButton1.setLGNV_backgroundAllow(false);
        lgnvButton1.setLGNV_hoverAllow(false);
        lgnvButton1.setLGNV_lineAllow(false);
        lgnvButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBG3Layout = new javax.swing.GroupLayout(pnlBG3);
        pnlBG3.setLayout(pnlBG3Layout);
        pnlBG3Layout.setHorizontalGroup(
            pnlBG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBG3Layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(lgnvButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBG3Layout.setVerticalGroup(
            pnlBG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBG3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lgnvButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pnlBG.add(pnlBG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        main.home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lgnvButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvButton1ActionPerformed
        main.showOption.content("Bạn có muốn thoát không nà !!");
        if(main.showOption.result){
            System.exit(0);
        }
    }//GEN-LAST:event_lgnvButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIBRARY.lgnvButton btnLogin;
    private LIBRARY.lgnvPanel lblBG;
    private javax.swing.JLabel lblLogin;
    private LIBRARY.lgnvButton lgnvButton1;
    private LIBRARY.lgnvPanel pnlBG;
    private LIBRARY.lgnvPanel pnlBG3;
    private LIBRARY.lgnvTextField txtPass;
    private LIBRARY.lgnvTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
