/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author LGNV
 */
public class pnlDichVu extends javax.swing.JPanel {

    /**
     * Creates new form pnlDichVu
     */
    public pnlDichVu() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        this.setOpaque(true);
    }
    
    String IDDichVu = "";
    public  void setID(String ID){
         IDDichVu = ID;
    }
    public String getID(){
        return IDDichVu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lgnvPanel1 = new LIBRARY.lgnvPanel();
        lblGia = new javax.swing.JLabel();
        lblTenDichVu = new javax.swing.JLabel();

        lgnvPanel1.setBackground(new java.awt.Color(255, 255, 255));
        lgnvPanel1.setLGNV_borderRadius(30);
        lgnvPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgnvPanel1MouseClicked(evt);
            }
        });

        lblGia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGia.setText("30.000.000");

        lblTenDichVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_restaurant_50px_1.png"))); // NOI18N
        lblTenDichVu.setText("NumberOne");
        lblTenDichVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTenDichVu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout lgnvPanel1Layout = new javax.swing.GroupLayout(lgnvPanel1);
        lgnvPanel1.setLayout(lgnvPanel1Layout);
        lgnvPanel1Layout.setHorizontalGroup(
            lgnvPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTenDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lgnvPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGia, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );
        lgnvPanel1Layout.setVerticalGroup(
            lgnvPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lgnvPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTenDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGia)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lgnvPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnvPanel1MouseClicked
        if(evt.getClickCount() >=2){
            MyData.DataLuuTamDichVu.addChiTietDichVu(IDDichVu);
            main.dialogFormChoThue.fillPanelDichVuDangSuDung();
        }
    }//GEN-LAST:event_lgnvPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblGia;
    public javax.swing.JLabel lblTenDichVu;
    private LIBRARY.lgnvPanel lgnvPanel1;
    // End of variables declaration//GEN-END:variables
}
