/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author LGNV
 */
public class pnlDichVuDangSuDung extends javax.swing.JPanel {

    /**
     * Creates new form pnlDichVuDangSuDung
     */
    public pnlDichVuDangSuDung() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        this.setOpaque(true);
    }
    int fixBug = 1;
    
    String IDSanPham = "";
    public void setID(String ID){
        IDSanPham = ID;
    }
    public String getID(){
        return IDSanPham;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lgnvPanel1 = new LIBRARY.lgnvPanel();
        lblTenDichVu = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        btnClose = new LIBRARY.lgnvButton();
        btnClose1 = new LIBRARY.lgnvButton();
        btnClose2 = new LIBRARY.lgnvButton();

        lgnvPanel1.setLGNV_borderRadius(30);
        lgnvPanel1.setLGNV_lineColor(new java.awt.Color(52, 255, 8));
        lgnvPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTenDichVu.setText("Tên dịch vụ");
        lgnvPanel1.add(lblTenDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 127, 40));

        lblSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoLuong.setText("1");
        lgnvPanel1.add(lblSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 30, 40));

        lblGia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGia.setText("30,000,000");
        lgnvPanel1.add(lblGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 120, 40));

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_minus_26px.png"))); // NOI18N
        btnClose.setLGNV_backgroundAllow(false);
        btnClose.setLGNV_lineAllow(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        lgnvPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 33, 40));

        btnClose1.setBackground(new java.awt.Color(255, 255, 255));
        btnClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_close_window_26px_1.png"))); // NOI18N
        btnClose1.setLGNV_backgroundAllow(false);
        btnClose1.setLGNV_lineAllow(false);
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });
        lgnvPanel1.add(btnClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 33, 40));

        btnClose2.setBackground(new java.awt.Color(255, 255, 255));
        btnClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_add_26px.png"))); // NOI18N
        btnClose2.setLGNV_backgroundAllow(false);
        btnClose2.setLGNV_lineAllow(false);
        btnClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose2ActionPerformed(evt);
            }
        });
        lgnvPanel1.add(btnClose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 33, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        MyData.DataLuuTamDichVu.EditSLChiTietDichvu(IDSanPham, -1);
        main.dialogFormChoThue.fillPanelDichVuDangSuDung();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        MyData.DataLuuTamDichVu.deleteChiTietDichvu(IDSanPham);
        main.dialogFormChoThue.fillPanelDichVuDangSuDung();
    }//GEN-LAST:event_btnClose1ActionPerformed

    private void btnClose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose2ActionPerformed
        MyData.DataLuuTamDichVu.EditSLChiTietDichvu(IDSanPham, +1);
        main.dialogFormChoThue.fillPanelDichVuDangSuDung();
    }//GEN-LAST:event_btnClose2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public LIBRARY.lgnvButton btnClose;
    public LIBRARY.lgnvButton btnClose1;
    public LIBRARY.lgnvButton btnClose2;
    public javax.swing.JLabel lblGia;
    public javax.swing.JLabel lblSoLuong;
    public javax.swing.JLabel lblTenDichVu;
    private LIBRARY.lgnvPanel lgnvPanel1;
    // End of variables declaration//GEN-END:variables
}
