/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author LGNV
 */
public class pnlItemkhachHangChoThue extends javax.swing.JPanel {

    /**
     * Creates new form pnlDichVuDangSuDung
     */
    public pnlItemkhachHangChoThue() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        this.setOpaque(true);
    }

    
    String CMNDKhachHang = "";

    public void setCMND(String cmnd){
        CMNDKhachHang = cmnd;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lgnvPanel1 = new LIBRARY.lgnvPanel();
        lblCmnd = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        btnRemove = new LIBRARY.lgnvButton();

        lgnvPanel1.setLGNV_borderRadius(30);
        lgnvPanel1.setLGNV_lineColor(new java.awt.Color(52, 255, 8));
        lgnvPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgnvPanel1MouseClicked(evt);
            }
        });
        lgnvPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCmnd.setText("231306358");
        lgnvPanel1.add(lblCmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 100, 40));

        lblTen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTen.setText("Nguyễn Văn Lương");
        lgnvPanel1.add(lblTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 240, 40));

        btnRemove.setBackground(new java.awt.Color(255, 255, 255));
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_close_window_26px_1.png"))); // NOI18N
        btnRemove.setLGNV_backgroundAllow(false);
        btnRemove.setLGNV_lineAllow(false);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        lgnvPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 33, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        
        MyData.DataLuuTamListKhachHang.remove(CMNDKhachHang);
        if(CMNDKhachHang.equalsIgnoreCase(main.dialogFormChoThue.lblInfoCMND.getText())){
            main.dialogFormChoThue.lblInfoCMND.setText("");
            main.dialogFormChoThue.lblInfoKhachHang.setText("");
        }
        main.dialogFormChoThue.fillListKhachHang();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void lgnvPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnvPanel1MouseClicked
        if(evt.getClickCount()>=2){
            main.dialogFormChoThue.lblInfoKhachHang.setText(lblTen.getText());
            main.dialogFormChoThue.lblInfoCMND.setText(lblCmnd.getText());
        }
    }//GEN-LAST:event_lgnvPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public LIBRARY.lgnvButton btnRemove;
    public javax.swing.JLabel lblCmnd;
    public javax.swing.JLabel lblTen;
    private LIBRARY.lgnvPanel lgnvPanel1;
    // End of variables declaration//GEN-END:variables
}
