/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author LGNV
 */
public class pnlManagerKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form pnlManagerKhachHang
     */
    public pnlManagerKhachHang() {
        initComponents();
        css();
    }
    private void css(){
        scroll.setBackground(Color.white);
        scroll.setOpaque(false);
    }
    
    public void compile(){
        BLL.BLL_KhachHang.getALLData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lgnvPanel1 = new LIBRARY.lgnvPanel();
        pnlHeader = new LIBRARY.lgnvPanel();
        btnSua = new LIBRARY.lgnvButton();
        btnThem = new LIBRARY.lgnvButton();
        btnSua1 = new LIBRARY.lgnvButton();
        scroll = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        pnlPaddingLeft = new LIBRARY.lgnvPanel();

        setLayout(new java.awt.CardLayout());

        lgnvPanel1.setBackground(new java.awt.Color(255, 255, 255));
        lgnvPanel1.setLGNV_lineAllow(false);
        lgnvPanel1.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setLGNV_lineAllow(false);
        pnlHeader.setPreferredSize(new java.awt.Dimension(889, 80));

        btnSua.setBackground(new java.awt.Color(100, 89, 242));
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_filter_25px.png"))); // NOI18N
        btnSua.setText("Lọc");
        btnSua.setLGNV_ShadowAllow(true);
        btnSua.setLGNV_borderRadius(60);
        btnSua.setLGNV_lineAllow(false);
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(100, 89, 242));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_add_25px.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setLGNV_ShadowAllow(true);
        btnThem.setLGNV_borderRadius(60);
        btnThem.setLGNV_lineAllow(false);
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua1.setBackground(new java.awt.Color(100, 89, 242));
        btnSua1.setForeground(new java.awt.Color(255, 255, 255));
        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_synchronize_25px.png"))); // NOI18N
        btnSua1.setText("Reload");
        btnSua1.setLGNV_ShadowAllow(true);
        btnSua1.setLGNV_borderRadius(60);
        btnSua1.setLGNV_lineAllow(false);
        btnSua1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSua1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lgnvPanel1.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã khách Hàng", "Tên Khách Hàng", "CMND", "Loại Khách Hàng", "SDT", "DiaChi", "Ngày Sinh", "Giới Tính", "Mô Tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang.setRowHeight(30);
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        scroll.setViewportView(tblKhachHang);

        lgnvPanel1.add(scroll, java.awt.BorderLayout.CENTER);

        pnlPaddingLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnlPaddingLeft.setLGNV_lineAllow(false);
        pnlPaddingLeft.setPreferredSize(new java.awt.Dimension(50, 447));

        javax.swing.GroupLayout pnlPaddingLeftLayout = new javax.swing.GroupLayout(pnlPaddingLeft);
        pnlPaddingLeft.setLayout(pnlPaddingLeftLayout);
        pnlPaddingLeftLayout.setHorizontalGroup(
            pnlPaddingLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlPaddingLeftLayout.setVerticalGroup(
            pnlPaddingLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        lgnvPanel1.add(pnlPaddingLeft, java.awt.BorderLayout.LINE_START);

        add(lgnvPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        main.dialogLocKhachHang.setVisible(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        main.dialogFormKhachHang.checkNew(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        compile();
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        if(evt.getClickCount()>=2){
            BLL.BLL_KhachHang.setDataToForm(BLL.BLL_KhachHang.getIDTable());
            main.dialogFormKhachHang.checkNew(false);
        }
        
    }//GEN-LAST:event_tblKhachHangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIBRARY.lgnvButton btnSua;
    private LIBRARY.lgnvButton btnSua1;
    private LIBRARY.lgnvButton btnThem;
    private LIBRARY.lgnvPanel lgnvPanel1;
    private LIBRARY.lgnvPanel pnlHeader;
    private LIBRARY.lgnvPanel pnlPaddingLeft;
    private javax.swing.JScrollPane scroll;
    public static javax.swing.JTable tblKhachHang;
    // End of variables declaration//GEN-END:variables
}
