/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_Phong;
import BLL.BLL_Thue;
import DAL.DAL_Phong;
import DTO.DTO_Phong;
import DTO.PhieuThue;
import java.awt.Color;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Panel;
import java.awt.Toolkit;
import java.awt.Window;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JPanel;

/**
 *
 * @author LGNV
 */
public class pnlTabHome extends javax.swing.JPanel {

    /**
     * Creates new form pnlTabManager
     */
    public pnlTabHome() {
        initComponents();
    }

    public void compile() {

        ArrayList<DTO_Phong> list = DAL_Phong.select();

        JPanel pnlFix = new JPanel();
        addComponent(list);

//        pnlFix.setBackground(Color.red);
//        pnlfull.add(pnlFix);
//        pnlFix.setSize(new Dimension(500, 500));
    }
    
    

    public void filterPhong(String MaTinhTrang) {
        ArrayList<DTO_Phong> list = DAL_Phong.select();
        ArrayList<DTO_Phong> list2 = new ArrayList<>();

        for (DTO_Phong phong : list) {
            if (phong.getMaTinhTrang().equalsIgnoreCase(MaTinhTrang)) {
                list2.add(phong);
            }
        }

        addComponent(list2);

    }

    public void addComponent(ArrayList<DTO_Phong> list) {
        repaint();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        int getColumn = (int) (width - 350) / 250;
        JPanel pnlALLShowPhong = new javax.swing.JPanel();
        pnlfull.removeAll();
        for (int i = 0; i < list.size(); i++) {
            DTO_Phong phong = list.get(i);
            if (i % getColumn == 0) {
                pnlALLShowPhong = new javax.swing.JPanel();
                pnlALLShowPhong.setSize(new Dimension(0, 150));
                pnlALLShowPhong.setLayout(new java.awt.GridBagLayout());
                pnlALLShowPhong.setBackground(Color.WHITE);
            }
            
            pnlShowPhong pnlShowPhong = new GUI.pnlShowPhong();
            
            pnlShowPhong.lblTenPhong.setText("Phòng" + phong.getMaPhong());
            pnlALLShowPhong.add(pnlShowPhong, new java.awt.GridBagConstraints());
            pnlShowPhong.setID(phong.getMaPhong());
            

            setBacgroundTinhTrangPhong(phong, pnlShowPhong);

            if (i % getColumn == 0) {
                pnlfull.add(pnlALLShowPhong);
            }
        }
        this.setVisible(false);
        repaint();
    }

    public void setBacgroundTinhTrangPhong(DTO_Phong phong, pnlShowPhong pnlShowPhong) {
        String TinhTrangPhong = phong.getMaTinhTrang();
        DTO.PhieuThue phieuThue  = BLL_Thue.checkPhong(phong.getMaPhong());
        if (TinhTrangPhong.equalsIgnoreCase("BAN")) {
            pnlShowPhong.lblThongBao.setText("Phòng mới trả");
            pnlShowPhong.pnlAllPhong.setBackground(new Color(100, 89, 242));
        } else if (TinhTrangPhong.equalsIgnoreCase("DAT")) {
            
            pnlShowPhong.lblThongBao.setText("Đã được đặt");
            pnlShowPhong.pnlAllPhong.setBackground(new Color(202, 162, 16));
        }
        if ( phieuThue!= null) {
            pnlShowPhong.lblThongBao.setText(phong.getMoTa());
            pnlShowPhong.pnlAllPhong.setBackground(new Color(245, 36, 7));
            pnlShowPhong.setIDPhieuThue(phieuThue.getMaPhieuThue());
        }
        if (TinhTrangPhong.equalsIgnoreCase("DON")) {
            pnlShowPhong.lblThongBao.setText("Phòng đang dọn");
            pnlShowPhong.pnlAllPhong.setBackground(new Color(98, 66, 202));
        } else {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lgnvPanel1 = new LIBRARY.lgnvPanel();
        lgnvPanel2 = new LIBRARY.lgnvPanel();
        lgnvPanel4 = new LIBRARY.lgnvPanel();
        lgnvPanel3 = new LIBRARY.lgnvPanel();
        lgnvButton1 = new LIBRARY.lgnvButton();
        lgnvButton2 = new LIBRARY.lgnvButton();
        lgnvButton3 = new LIBRARY.lgnvButton();
        lgnvButton4 = new LIBRARY.lgnvButton();
        lgnvButton5 = new LIBRARY.lgnvButton();
        lgnvButton6 = new LIBRARY.lgnvButton();
        pnlCenter = new LIBRARY.lgnvPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlfull = new LIBRARY.lgnvPanel();

        lgnvPanel1.setBackground(new java.awt.Color(255, 255, 255));
        lgnvPanel1.setLGNV_lineAllow(false);
        lgnvPanel1.setLayout(new java.awt.BorderLayout());

        lgnvPanel2.setBackground(new java.awt.Color(100, 89, 242));
        lgnvPanel2.setLGNV_lineAllow(false);
        lgnvPanel2.setPreferredSize(new java.awt.Dimension(250, 457));

        lgnvPanel4.setBackground(new java.awt.Color(255, 255, 255));
        lgnvPanel4.setLGNV_ShaDownAllow(true);
        lgnvPanel4.setLGNV_borderRadius(50);
        lgnvPanel4.setLGNV_lineAllow(false);

        lgnvPanel3.setBackground(new java.awt.Color(255, 255, 255));
        lgnvPanel3.setLGNV_lineAllow(false);
        lgnvPanel3.setLayout(new java.awt.GridLayout(0, 1, 20, 0));

        lgnvButton1.setBackground(new java.awt.Color(4, 163, 11));
        lgnvButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        lgnvButton1.setForeground(new java.awt.Color(255, 255, 255));
        lgnvButton1.setText("Trống");
        lgnvButton1.setLGNV_ShadowAllow(true);
        lgnvButton1.setLGNV_ShadownPixel(10);
        lgnvButton1.setLGNV_borderRadius(30);
        lgnvButton1.setLGNV_lineAllow(false);
        lgnvButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgnvButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvButton1ActionPerformed(evt);
            }
        });
        lgnvPanel3.add(lgnvButton1);

        lgnvButton2.setBackground(new java.awt.Color(245, 36, 7));
        lgnvButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        lgnvButton2.setForeground(new java.awt.Color(255, 255, 255));
        lgnvButton2.setText("Thuê");
        lgnvButton2.setLGNV_ShadowAllow(true);
        lgnvButton2.setLGNV_ShadownPixel(10);
        lgnvButton2.setLGNV_borderRadius(30);
        lgnvButton2.setLGNV_lineAllow(false);
        lgnvButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgnvButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvButton2ActionPerformed(evt);
            }
        });
        lgnvPanel3.add(lgnvButton2);

        lgnvButton3.setBackground(new java.awt.Color(100, 89, 242));
        lgnvButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        lgnvButton3.setForeground(new java.awt.Color(255, 255, 255));
        lgnvButton3.setText("Bẩn");
        lgnvButton3.setLGNV_ShadowAllow(true);
        lgnvButton3.setLGNV_ShadownPixel(10);
        lgnvButton3.setLGNV_borderRadius(30);
        lgnvButton3.setLGNV_lineAllow(false);
        lgnvButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgnvButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvButton3ActionPerformed(evt);
            }
        });
        lgnvPanel3.add(lgnvButton3);

        lgnvButton4.setBackground(new java.awt.Color(202, 162, 16));
        lgnvButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        lgnvButton4.setForeground(new java.awt.Color(255, 255, 255));
        lgnvButton4.setText("Được Đặt");
        lgnvButton4.setLGNV_ShadowAllow(true);
        lgnvButton4.setLGNV_ShadownPixel(10);
        lgnvButton4.setLGNV_borderRadius(30);
        lgnvButton4.setLGNV_lineAllow(false);
        lgnvButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgnvButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvButton4ActionPerformed(evt);
            }
        });
        lgnvPanel3.add(lgnvButton4);

        lgnvButton5.setBackground(new java.awt.Color(98, 66, 202));
        lgnvButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        lgnvButton5.setForeground(new java.awt.Color(255, 255, 255));
        lgnvButton5.setText("Đang dọn");
        lgnvButton5.setLGNV_ShadowAllow(true);
        lgnvButton5.setLGNV_ShadownPixel(10);
        lgnvButton5.setLGNV_borderRadius(30);
        lgnvButton5.setLGNV_lineAllow(false);
        lgnvButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgnvButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvButton5ActionPerformed(evt);
            }
        });
        lgnvPanel3.add(lgnvButton5);

        lgnvButton6.setBackground(new java.awt.Color(98, 66, 202));
        lgnvButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        lgnvButton6.setForeground(new java.awt.Color(255, 255, 255));
        lgnvButton6.setText("Tất Cả");
        lgnvButton6.setLGNV_ShadowAllow(true);
        lgnvButton6.setLGNV_ShadownPixel(10);
        lgnvButton6.setLGNV_borderRadius(30);
        lgnvButton6.setLGNV_lineAllow(false);
        lgnvButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgnvButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvButton6ActionPerformed(evt);
            }
        });
        lgnvPanel3.add(lgnvButton6);

        javax.swing.GroupLayout lgnvPanel4Layout = new javax.swing.GroupLayout(lgnvPanel4);
        lgnvPanel4.setLayout(lgnvPanel4Layout);
        lgnvPanel4Layout.setHorizontalGroup(
            lgnvPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(lgnvPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lgnvPanel4Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(lgnvPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        lgnvPanel4Layout.setVerticalGroup(
            lgnvPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
            .addGroup(lgnvPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lgnvPanel4Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(lgnvPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout lgnvPanel2Layout = new javax.swing.GroupLayout(lgnvPanel2);
        lgnvPanel2.setLayout(lgnvPanel2Layout);
        lgnvPanel2Layout.setHorizontalGroup(
            lgnvPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lgnvPanel2Layout.setVerticalGroup(
            lgnvPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lgnvPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(lgnvPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        lgnvPanel1.add(lgnvPanel2, java.awt.BorderLayout.LINE_START);

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlCenter.setLGNV_lineAllow(false);
        pnlCenter.setMaximumSize(new java.awt.Dimension(1, 32767));
        pnlCenter.setLayout(new java.awt.CardLayout());

        jScrollPane1.setToolTipText("");

        pnlfull.setLayout(new javax.swing.BoxLayout(pnlfull, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlfull);

        pnlCenter.add(jScrollPane1, "card3");

        lgnvPanel1.add(pnlCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lgnvButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvButton1ActionPerformed
        filterPhong("TRO");
    }//GEN-LAST:event_lgnvButton1ActionPerformed

    private void lgnvButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvButton2ActionPerformed
        filterPhong("THU");
    }//GEN-LAST:event_lgnvButton2ActionPerformed

    private void lgnvButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvButton3ActionPerformed
        filterPhong("BAN");
    }//GEN-LAST:event_lgnvButton3ActionPerformed

    private void lgnvButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvButton4ActionPerformed
        filterPhong("DAT");
    }//GEN-LAST:event_lgnvButton4ActionPerformed

    private void lgnvButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvButton5ActionPerformed
        filterPhong("DON");
    }//GEN-LAST:event_lgnvButton5ActionPerformed

    private void lgnvButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvButton6ActionPerformed
        compile();
    }//GEN-LAST:event_lgnvButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private LIBRARY.lgnvButton lgnvButton1;
    private LIBRARY.lgnvButton lgnvButton2;
    private LIBRARY.lgnvButton lgnvButton3;
    private LIBRARY.lgnvButton lgnvButton4;
    private LIBRARY.lgnvButton lgnvButton5;
    private LIBRARY.lgnvButton lgnvButton6;
    private LIBRARY.lgnvPanel lgnvPanel1;
    private LIBRARY.lgnvPanel lgnvPanel2;
    private LIBRARY.lgnvPanel lgnvPanel3;
    private LIBRARY.lgnvPanel lgnvPanel4;
    public LIBRARY.lgnvPanel pnlCenter;
    private LIBRARY.lgnvPanel pnlfull;
    // End of variables declaration//GEN-END:variables
}
